services:
    o0johntam0o.archive.listener:
        class: o0johntam0o\archive\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - @auth
            - @config
            - @request
            - %core.php_ext%
        tags:
            - { name: event.listener }

    o0johntam0o.archive.controller:
        class: o0johntam0o\archive\controller\main
        arguments:
            - @controller.helper
            - @template
            - @user
            - @config
            - @auth
            - @request
            - @dbal.conn
            - @passwords.manager
            - %core.root_path%
            - %core.php_ext%
